name: Push kaggle kernels

on: 
  push:
    branches:
      - main
    paths:
      - notebooks/current.ipynb
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    name: Python ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Kaggle deploy from existing metadata file
      uses: Joel-hanson/kaggle-kernel-actions@master
      with:
        kaggle_username: ${{ secrets.kaggle_username }}
        kaggle_key: ${{ secrets.kaggle_key }}
        kaggle_make_new_kernel: true
        kaggle_metadata_path: kernel-metadata.json
        kernel_id: domenicocacace/homework-1
